version: '3.7'

services:
  postgresql:
    image: postgres:12.0-alpine
    ports:
      - 5432:5432
    environment:
      - PGDATA=/postgresql
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
    volumes:
      - db-volume:/postgresql

volumes:
  db-volume:
